### ISSUE TITLE
Messages can be long

### ISSUE THREAD

**Issue by WA9ACE** [fractaledmind/solid_errors#5]
For example, when setting up a new rails app with users and activeadmin, and producing a resource to manage users, you maybe presented with an exception from the source below.

https://github.com/activerecord-hackery/ransack/blob/main/lib/ransack/adapters/active_record/base.rb#L112

Producing this exception in `solid_errors`

```
Data too long for column 'message'
```

Messages of this size seem rare however, so I'm not sure if messages this long are something you necessarily want to support.

**Comment by fractaledmind** [comment]
Yeah, this is the inverse (sort of) of #1. There the issue was that MySQL has a max byte length for indexes. I am realizing now that I need to re-architect this part of the data model completely. Instead of a four column unique index, I will make the `message` column `text` and "fingerprint" the exceptions in Ruby and add a `fingerprint` column that has a unique index on that column alone. This will allow the content columns to be larger, the index to fit within size constraints, but the uniqueness logic that is needed to drive unresolving to still work.

I'll work on this shortly.
